version: '3.8'

services:
  ms-pedidos:
    image: YOUR_DOCKERHUB_USERNAME/ms-pedidos:latest
    container_name: ms-pedidos
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://ep-round-block-aqyanzt1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_TYHAhmZQ5az2
    restart: unless-stopped

  ms-guias:
    image: YOUR_DOCKERHUB_USERNAME/ms-guias:latest
    container_name: ms-guias
    ports:
      - "8082:8082"
    depends_on:
      - ms-pedidos
    environment:
      DB_URL: jdbc:postgresql://ep-round-block-aqyanzt1-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_TYHAhmZQ5az2
      PEDIDOS_SERVICE_URL: http://ms-pedidos:8081
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GCS_ACCESS_KEY: ${GCS_ACCESS_KEY}
      GCS_SECRET_KEY: ${GCS_SECRET_KEY}
    volumes:
      - ./efs-data:/app/efs
    restart: unless-stopped