server.port=8083
spring.application.name=ms-consumer

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Colas (mismas que ms-producer: este servicio solo consume de ellas)
rabbitmq.queue.guias=guias.despacho.cola1
rabbitmq.queue.guias.error=guias.despacho.cola2
rabbitmq.exchange.direct=guias.exchange
rabbitmq.routing-key.guias=guias.routing.key
rabbitmq.exchange.dlx=dlx.exchange
rabbitmq.routing-key.dlx=dlx.routing.key
